// This file must run last, so it is prefixed as such.
const unusedItems = [
    // Redundant bread
    "createfood:bun",
    // Competitors' Sandwiches
    "createfood:bread_slice_apple_jam",
    "createfood:bread_slice_bacon",
    "createfood:bread_slice_bacon_lettuce",
    "createfood:bread_slice_bacon_lettuce_tomato",
    "createfood:bread_slice_beetroot",
    "createfood:bread_slice_beetroot_lettuce",
    "createfood:bread_slice_berry_jam",
    "createfood:bread_slice_cheese",
    "createfood:bread_slice_chorus_fruit_jam",
    "createfood:bread_slice_glow_berry_jam",
    "createfood:bread_slice_honey",
    "createfood:bread_slice_lettuce",
    "createfood:bread_slice_lettuce_tomato",
    "createfood:bread_slice_melon_jam",
    "createfood:bread_slice_mutton",
    "createfood:bread_slice_mutton_beetroot",
    "createfood:bread_slice_peanut_butter",
    "createfood:apple_jam_sandwich",
    "createfood:bacon_sandwich",
    "createfood:bacon_sandwich_lettuce",
    "createfood:bacon_lettuce_tomato_sandwich",
    "createfood:beetroot_sandwich",
    "createfood:beetroot_lettuce_sandwich",
    "createfood:berry_jam_sandwich",
    "createfood:cheese_sandwich",
    "createfood:chorus_fruit_jam_sandwich",
    "createfood:glow_berry_jam_sandwich",
    "createfood:honey_sandwich",
    "createfood:lettuce_sandwich",
    "createfood:lettuce_tomato_sandwich",
    "createfood:melon_jam_sandwich",
    "createfood:mutton_sandwich",
    "createfood:mutton_beetroot_sandwich",
    "createfood:peanut_butter_sandwich",
    "createfood:cheese_and_sausage_biscuit_sandwich",
    "createfood:cheese_biscuit_sandwich",
    "createfood:sausage_biscuit_sandwich",
    "createfood:hot_cheese_and_sausage_biscuit_sandwich",
    "createfood:hot_cheese_biscuit_sandwich",
    "createfood:hot_sausage_biscuit_sandwich",
    "createfood:cheese_and_sausage_biscuit",
    "createfood:cheese_biscuit",
    "createfood:sausage_biscuit",
    "createfood:endermite_meatball_sandwich",
    "createfood:fried_egg_hash_brown_sandwich",
    "createfood:grilled_cheese_sandwich",
    "createfood:meatball_sandwich",
    "createfood:mutton_sandwich_beetroot",
    "createfood:peanut_butter_apple_jam_sandwich",
    "createfood:peanut_butter_chorus_fruit_jam_sandwich",
    "createfood:peanut_butter_melon_jam_sandwich",
    "createfood:strider_meatball_sandwich",
    "createfood:vegetable_sandwich_beetroot_lettuce",
    "createfood:vegetable_sandwich_lettuce_tomato",
    "farmersdelight:egg_sandwich",
    "farmersdelight:chicken_sandwich",
    "farmersdelight:bacon_sandwich",
    "garnished:peanut_cinder_sandwich",
    "createfood:bread_fried_egg",
    "createfood:bread_lettuce",
    "createfood:bread_lettuce_carrot",
    "garnished:phantom_burger",
    // Competitors' Burgers
    "createfood:beef_bun",
    "createfood:beef_bun_bacon",
    "createfood:beef_bun_bacon_lettuce",
    "createfood:beef_bun_bacon_lettuce_tomato",
    "createfood:beef_bun_lettuce",
    "createfood:beef_bun_lettuce_tomato",
    "createfood:beef_bun_onion",
    "createfood:beef_bun_onion_lettuce",
    "createfood:beef_bun_onion_lettuce_tomato",
    "createfood:beef_bun_onion_bacon",
    "createfood:beef_bun_onion_bacon_lettuce",
    "createfood:beef_bun_onion_bacon_lettuce_tomato",
    "createfood:beef_bun_peanut_butter",
    "createfood:beef_bun_peanut_butter_bacon",
    "createfood:cheese_and_beef_bun_peanut_butter_bacon",
    "createfood:cheese_and_beef_bun",
    "createfood:cheese_and_beef_bun_bacon",
    "createfood:cheese_and_beef_bun_bacon_lettuce",
    "createfood:cheese_and_beef_bun_bacon_lettuce_tomato",
    "createfood:cheese_and_beef_bun_lettuce",
    "createfood:cheese_and_beef_bun_lettuce_tomato",
    "createfood:cheese_and_beef_bun_onion",
    "createfood:cheese_and_beef_bun_onion_lettuce"  ,
    "createfood:cheese_and_beef_bun_onion_lettuce_tomato",
    "createfood:cheese_and_beef_bun_onion_bacon",
    "createfood:cheese_and_beef_bun_onion_bacon_lettuce",
    "createfood:cheese_and_beef_bun_onion_bacon_lettuce_tomato",
    "createfood:cheese_and_beef_bun_peanut_butter",
    "createfood:cheese_and_beef_bun_peanut_butter_bacon",
    "createfood:chicken_bun",
    "createfood:chicken_bun_lettuce",
    "createfood:chicken_bun_bacon_lettuce",
    "createfood:chicken_bun_lettuce_tomato",
    "createfood:cheese_and_chicken_bun",
    "createfood:cheese_and_chicken_bun_lettuce",
    "createfood:cheese_and_chicken_bun_bacon_lettuce",
    "createfood:cheese_and_chicken_bun_lettuce_tomato",
    "createfood:eggplant_bun",
    "createfood:eggplant_bun_lettuce",
    "createfood:eggplant_bun_lettuce_tomato",
    "createfood:cheese_and_eggplant_bun",
    "createfood:cheese_and_eggplant_bun_lettuce",
    "createfood:cheese_and_eggplant_bun_lettuce_tomato",
    "createfood:dragon_bun",
    "createfood:dragon_bun_crimson_fungus",
    "createfood:dragon_bun_warped_fungus",
    "createfood:hamburger",
    "createfood:hamburger_bacon",
    "createfood:hamburger_bacon_lettuce",
    "createfood:hamburger_bacon_lettuce_tomato",
    "createfood:hamburger_lettuce",
    "createfood:hamburger_lettuce_tomato",
    "createfood:hamburger_onion",
    "createfood:hamburger_onion_lettuce",
    "createfood:hamburger_onion_lettuce_tomato",
    "createfood:hamburger_onion_bacon",
    "createfood:hamburger_onion_bacon_lettuce",
    "createfood:hamburger_onion_bacon_lettuce_tomato",
    "createfood:hamburger_peanut_butter",
    "createfood:hamburger_peanut_butter_bacon",
    "createfood:cheeseburger_peanut_butter_bacon",
    "createfood:cheeseburger",
    "createfood:cheeseburger_bacon",
    "createfood:cheeseburger_bacon_lettuce",
    "createfood:cheeseburger_bacon_lettuce_tomato",
    "createfood:cheeseburger_lettuce",
    "createfood:cheeseburger_lettuce_tomato",
    "createfood:cheeseburger_onion",
    "createfood:cheeseburger_onion_lettuce"  ,
    "createfood:cheeseburger_onion_lettuce_tomato",
    "createfood:cheeseburger_onion_bacon",
    "createfood:cheeseburger_onion_bacon_lettuce",
    "createfood:cheeseburger_onion_bacon_lettuce_tomato",
    "createfood:cheeseburger_peanut_butter",
    "createfood:cheeseburger_peanut_butter_bacon",
    "createfood:chicken_burger",
    "createfood:chicken_burger_lettuce",
    "createfood:chicken_burger_bacon_lettuce",
    "createfood:chicken_burger_lettuce_tomato",
    "createfood:chicken_cheeseburger",
    "createfood:chicken_cheeseburger_lettuce",
    "createfood:chicken_cheeseburger_bacon_lettuce",
    "createfood:chicken_cheeseburger_lettuce_tomato",
    "createfood:eggplant_burger",
    "createfood:eggplant_burger_lettuce",
    "createfood:eggplant_burger_lettuce_tomato",
    "createfood:eggplant_cheeseburger",
    "createfood:eggplant_cheeseburger_lettuce",
    "createfood:eggplant_cheeseburger_lettuce_tomato",
    "createfood:dragon_burger",
    "createfood:dragon_burger_crimson_fungus",
    "createfood:dragon_burger_warped_fungus",
    "farmersdelight:hamburger",
    "culturaldelights:eggplant_burger",
    "culturaldelights:mutton_sandwich",
    // Extra Toast
    "createfood:toast",
    // Ube
    "createfood:ube_cream_frosting_bucket",
    "createfood:ube_cream_frosting_bottle",
    "createfood:raw_ube_cake_base",
    "createfood:raw_ube_cookie",
    "createfood:ube_sugar_dough",
    "createfood:ube_cake_base",
    "createfood:ube_cream_frosted_ube_cake",
    // Coffee
    "createfood:coffee_toffee",
    "createfood:coffee_toffee_fudge",
    "createfood:coffee_toffee_bucket",
    "createfood:coffee_toffee_fudge_bucket",
    "createfood:marshmallow_coffee_toffee_fudge",
    "createfood:dried_coffee_beans",
    // Cinimal Sweet Roll
    "createfood:raw_cinnamon_sweet_roll_base",
    "createfood:cinnamon_sweet_roll_base",
    // Corn Flour
    "createfood:corn_flour",
    // Smoked Corn Stick
    "createfood:smoked_corn_stick",
    // Create Food's Nachos
    "createfood:nacho_bowl",
    // Redundant Sliced Vegetables
    "createfood:sliced_beetroot",
    "createfood:sliced_carrot",
    "createfood:sliced_tomato",
    // Personal Key
    "storagedrawers:personal_key_cofh",
    // Cookies
    "createfood:raw_chorus_cookie",
    "createfood:raw_soul_berry_cookie",
    "createfood:raw_spider_eye_cookie",
    "createfood:raw_ginger_cookie",
    "createfood:raw_green_tee_cookie",
    "createfood:raw_flesh_cookie",
    // Magma Cream Marshmallow
    "createfood:magma_cream_marshmallow",
    "createfood:magma_cream_marshmallow_stick",
    // Redundant Items
    "createfood:caramel_popcorn",
    "createfood:chorus_fruit_popsicle",
    // Apple Cider
    "farmersdelight:apple_cider",
    // Non-hatchable dragon egg
    "ends_delight:non_hatchable_dragon_egg",
    // Copycats
    "create_connected:copycat_block",
    "create_connected:copycat_slab",
    "create_connected:copycat_beam",
    "create_connected:copycat_vertical_step",
    "create_connected:copycat_stairs",
    "create_connected:copycat_fence",
    "create_connected:copycat_catwalk",
    "create_connected:copycat_box",
    "create_connected:copycat_board",
    "create_connected:copycat_wall",
    "create_connected:copycat_fence_gate",
    // Cultural Delight's corn
    "culturaldelights:corn_kernels",
    "culturaldelights:corn_cob",
    "culturaldelights:popcorn",
    "culturaldelights:corn_dough",
    "culturaldelights:creamed_corn",
    "culturaldelights:tortilla",
    "culturaldelights:chicken_taco",
    "culturaldelights:fish_taco",
    "culturaldelights:tortilla_chips",
];

const unusedTags = [
    "#forge:paprika",
    "#forge:bread_slice",
    "#forge:espresso_powder",
];

ServerEvents.tags("item", event => {
    for (let item of unusedItems) {
        event.removeAllTagsFrom(item);
    }
});

ServerEvents.recipes(event => {
    event.remove(unusedItems.map(s => {
        return {
            output: s
        };
    }));

    event.remove(unusedItems.concat(unusedTags).    map(s => {
        return {
            input: s
        }
    }));

    event.remove("createfood:minecraft/crafting/pasta_plate_slimeballs_from_crafting");
    event.replaceInput("copycats:crafting/copycat_vertical_stairs_from_conversion", "#copycats:copycat_stairs", "copycats:copycat_stairs");
});